### ISSUE TITLE
该代码可以直接运行在github上吗?

### ISSUE THREAD

**Issue by gongkuihua** [gaop-0561/PicBed4MWeb#2]
利用github免费网站能力,可以将该服务直接运行在github上吗?,这样一来就不用在本地启动服务来,而且换电脑无需装,该项目所需要的环境,只需要配置github网站地址就可以了

**Comment by gaop-0561** [comment]
应该不行的吧，这个需要一个支持NodeJS的服务器来运行这个程序，GitHub貌似只能发布静态页面
